# Generated by Django 5.1.2 on 2024-11-26 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reps', models.PositiveIntegerField()),
                ('calculated_rm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_maxes', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_maxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
