# Generated by Django 5.1.2 on 2024-11-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_repmax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_management_profile', 'Can view Management profile')]},
        ),
    ]
