# Generated by Django 5.1.2 on 2024-12-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('AMRAP', 'AMRAP'), ('Death By', 'Death By'), ('EMOM', 'EMOM'), ('For time', 'For time')], max_length=30)),
                ('loading', models.CharField(choices=[('BW', 'BW'), ('Half BW', 'Half BW'), ('.75 BW', '.75 BW')], max_length=30)),
                ('exercises', models.ManyToManyField(related_name='complexes', to='workouts.exercise')),
            ],
        ),
    ]
