# Generated by Django 5.1.2 on 2024-12-02 21:01

import django.db.models.deletion
import django.utils.timezone
import workoutApp.common_utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600)),
                ('calories', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, validators=[workoutApp.common_utils.validators.date_today_validator])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Other', 'Other')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
